// flow-typed signature: 85d47ff0679f22427de6164da766239e
// flow-typed version: <<STUB>>/pg-error_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-error/test/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-error/index' {
  declare module.exports: $Exports<'pg-error'>;
}
declare module 'pg-error/index.js' {
  declare module.exports: $Exports<'pg-error'>;
}
declare module 'pg-error/test/index_test.js' {
  declare module.exports: $Exports<'pg-error/test/index_test'>;
}
